env: development
system:
  log_level: info
  parallelism: 1
  scheduler:
    queue:
      size: 0
      type: fifo
    retry: 3
    timeout: 1h
  executor:
    workspace: build/workspace
  build_output_dir: build/output
  data_dir: .bbq
tasks:
  workspace: SOURCES
  source: bbq.workflows.example
  build_packages:


